development:
  adapter: postgresql
  encoding: unicode
  database: ebay_development
  pool: 5
  username: rachelminto
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ebay_test
  pool: 5
  username: rachelminto
  password:
