development:
  adapter: postgresql
  encoding: unicode
  database: ebay_development
  pool: 5
  username: myapp
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ebay_test
  pool: 5
  username: myapp
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ebay
  pool: 20
  encoding: utf8
  username: root
  password:
  host: https://ebay-description.herokuapp.com/